name: spotify-box
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    
jobs:
  updateTopTracks:
   runs-on: ubuntu-latest
   steps:
    - name: Check out repo
        uses: actions/checkout@v2
    - name: Clone & run
        run: |-
          git clone https://github.com/izayl/spotify-box.git
          cd spotify-box && npm install
       env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e7f6c5977ce7c0a7ae7a7a3d177b02ae
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
