name: spotify-box
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    
jobs:
  updateTopTracks:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: git clone https://github.com/izayl/spotify-box.git
     - run: cd spotify-box && npm install
     - name: Update
       run: ./izayl/spotify-box
       env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e7f6c5977ce7c0a7ae7a7a3d177b02ae
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
